### ISSUE TITLE
Add https://github.com/MitjaNemec/ReplicateLayout

### ISSUE THREAD

**Issue by CameronBrooks11** [joanbono/awesome-kicad#10]
This KiCad extension replicates the PCB layout of one hierarchical sheet to other sheets based on hierarchical sheets in Eeschema, supporting complex hierarchies, including subsheets, and replicating footprints, zones, tracks, text, and drawings, provided the source section is entirely within a single hierarchical sheet and the destinations are copies of the same sheet.

NOT MY LIB, but I've found it useful.

**Comment by joanbono** [comment]
Thanks for contributing
