### ISSUE TITLE
Add AntMicro utility libs

### ISSUE THREAD

**Issue by CameronBrooks11** [joanbono/awesome-kicad#13]
open-source utility dedicated to generating 3D models of Printed Circuit Boards (PCBs) in Blender (.blend) format:
https://github.com/antmicro/gerber2blend

takes PCB production files as input (Gerber, drill files, stackup information) and simulates trace SI performance using openEMS - a free and open electromagnetic field solver that uses the FDTD method:
https://github.com/antmicro/gerber2ems

**Comment by CameronBrooks11** [comment]
promise im done now :)

**Comment by joanbono** [comment]
Thanks for contributing!
