### ISSUE TITLE
Official library repos are wrong

### ISSUE THREAD

**Issue by kliment** [joanbono/awesome-kicad#7]
Hello! I'm a member of the KiCad library team. Your links to the "official KiCad symbols" and "official KiCad footprints" are out of date - we moved from github to gitlab a few years back, and the github repositories have not been maintained for years. Would you be able to update the links?

The correct links are as follows.

Footprints: https://gitlab.com/kicad/libraries/kicad-footprints
Symbols: https://gitlab.com/kicad/libraries/kicad-symbols
3D models: https://gitlab.com/kicad/libraries/kicad-packages3D

All the library-related repos can be found at https://gitlab.com/kicad/libraries

**Comment by joanbono** [comment]
Thanks a lo @kliment ! Links updated!
