### ISSUE TITLE
New plugin: Import-LIB-KiCad-Plugin

### ISSUE THREAD

**Issue by Steffen-W** [joanbono/awesome-kicad#9]
Hi, please add my plugin to your list. 
It is a GUI for very easy import of libraries (Footprint Symbol and 3D) from Octopart, Samacsys and Snapeda. 

https://github.com/Steffen-W/Import-LIB-KiCad-Plugin

**Comment by joanbono** [comment]
Thanks a lot for the contribution, @Steffen-W !

Your plugin has been added!
